import Link from 'next/link';
import { ArrowRight, Sparkles, Play, Check, BookOpen, MoveUpRight } from 'lucide-react';
import { PublicHeader, Brand } from '@/components/ui';
import { templates } from '@/lib/types';
export default function Home() { return <><PublicHeader/><main>
  <section className="hero"><div className="hero-copy"><p className="eyebrow"><span className="status-dot"/> IDEIAS QUE CONECTAM. AULAS QUE ENCANTAM.</p><h1>O conhecimento<br/>fica melhor<br/>quando vira <em>descoberta.</em></h1><p>Transforme seu conteúdo em atividades interativas.<br className="desktop-break"/> Crie, compartilhe e veja a aprendizagem acontecer.</p><div className="hero-actions"><Link className="button" href="/cadastro/">Criar minha primeira atividade <ArrowRight size={18}/></Link><Link className="text-button" href="/explorar/">Explorar ideias <MoveUpRight size={17}/></Link></div><div className="hero-note"><span><Check size={14}/> Comece gratuitamente</span><span><Check size={14}/> Alunos jogam sem conta</span></div></div>
  <div className="hero-scene" aria-label="Exemplo ilustrativo de um quiz sobre o Sistema Solar"><div className="orbit orbit-one"/><div className="orbit orbit-two"/><span className="scene-spark">✳</span><div className="floating-note"><span>✦</span> Uma ideia, muitos jeitos de aprender</div><div className="example-card"><div className="example-top"><span>CIÊNCIAS · 6º ANO</span><span>01 / 05</span></div><div className="solar-art"><div className="planet-ring"/><div className="planet"/><span className="star s1">✧</span><span className="star s2">✦</span><span className="little-planet"/></div><h3>Qual é o maior planeta<br/>do Sistema Solar?</h3><div className="example-answers"><span>Terra</span><span className="correct">Júpiter <Check size={16}/></span><span>Marte</span><span>Saturno</span></div><div className="example-progress"><i/></div></div><div className="floating-score"><span>✧</span><div><b>Aprender pode ser assim.</b><small>Mais curiosidade. Mais participação.</small></div></div><span className="scene-doodle">↗</span></div></section>
  <div className="subject-strip"><span>UM ESPAÇO PARA TODAS AS DESCOBERTAS</span><b>Ciências</b><i>✦</i><b>Matemática</b><i>✦</i><b>Português</b><i>✦</i><b>História</b><i>✦</i><b>E muito mais</b></div>
  <section id="formatos" className="section"><div className="section-heading"><div><p className="eyebrow">UM CONTEÚDO. NOVAS POSSIBILIDADES.</p><h2>Cada turma tem seu jeito de aprender.</h2></div><p>Escolha o formato que combina com sua aula.<br/>Troque de jogo sem reescrever as perguntas.</p></div><div className="template-grid">{templates.map(t => <Link className={`template-card ${t.color}`} key={t.id} href={`/cadastro/`}><span className="template-symbol">{t.symbol}</span><div><h3>{t.name}</h3><p>{t.description}</p></div><ArrowRight size={19}/></Link>)}</div></section>
  <section className="how-section section"><div><p className="eyebrow">DO PLANEJAMENTO À PARTICIPAÇÃO</p><h2>Sua próxima aula,<br/><em>cheia de possibilidades.</em></h2><p className="muted">Menos tempo preparando.<br/>Mais tempo acompanhando cada descoberta.</p><Link className="button" href="/cadastro/">Vamos criar juntos <ArrowRight size={17}/></Link></div><div className="steps">{[['01', 'Dê forma à sua ideia', 'Escreva as perguntas ou use a IA para preparar um rascunho.'], ['02', 'Escolha como jogar', 'Quiz, cartões ou pares: o conteúdo é o mesmo, a experiência muda.'], ['03', 'Conecte sua turma', 'Compartilhe um link ou código. Acompanhe os resultados no seu painel.']].map(([n, title, desc]) => <div className="step" key={n}><span>{n}</span><div><h3>{title}</h3><p>{desc}</p></div></div>)}</div></section>
  <section className="ai-banner"><div className="ai-badge"><Sparkles size={35}/></div><div><p className="eyebrow">UMA MÃOZINHA PARA SUAS IDEIAS</p><h2>Você traz o tema. A IA ajuda a começar.</h2><p>Gere perguntas, revise com seu olhar de professor e deixe a aula com a sua cara.</p></div><Link className="button cream" href="/dashboard/ia/">Conhecer o criador <ArrowRight size={17}/></Link></section>
  </main><footer><Brand/><span>Conectando ideias. Cultivando descobertas.</span><Link href="/jogar/">Participar de uma atividade <Play size={14}/></Link></footer></>; }
