'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { Play, Pencil, Copy, Share2, Trash2, Heart, Search, ArrowRight, Plus, BookOpen, Users, Trophy, BarChart3 } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { api, post } from '@/lib/api';
import { Activity, subjects, templates } from '@/lib/types';
import { Empty, ErrorMessage, Loading, Modal, PageHeading } from './ui';
import { useAuth } from './auth';

export function ShareModal({ activity, close }: { activity: Activity; close: () => void }) {
  const [copied, setCopied] = useState(false); const [error, setError] = useState('');
  const url = `${window.location.origin}/jogar/?codigo=${activity.code}`;
  return <Modal title="Uma descoberta para compartilhar" close={close}><p className="muted">Envie para sua turma. Cada aluno pode entrar com um apelido.</p><div className="qr"><QRCodeSVG value={url} size={150}/><div><span className="eyebrow">CÓDIGO DA ATIVIDADE</span><strong>{activity.code}</strong><p>{activity.title}</p></div></div><label>Link da atividade<input value={url} readOnly onFocus={e => e.target.select()}/></label><ErrorMessage message={error}/><button className="button full" onClick={async () => { try { await navigator.clipboard.writeText(url); setCopied(true); } catch { setError('Selecione e copie o link acima.'); } }}><Copy size={16}/>{copied ? 'Link copiado!' : 'Copiar link'}</button><p className="small-text">{activity.visibility === 'private' ? 'Esta atividade é privada. Altere para “Com link” no editor para permitir convidados.' : 'Os resultados aparecerão no seu painel após cada partida.'}</p></Modal>;
}

export function ActivityCard({ activity, own, initiallySaved = false, onChange }: { activity: Activity; own?: boolean; initiallySaved?: boolean; onChange?: () => void }) {
  const [share, setShare] = useState(false); const [remove, setRemove] = useState(false); const [error, setError] = useState(''); const [busy, setBusy] = useState(false); const [saved, setSaved] = useState(initiallySaved); const [notice, setNotice] = useState(''); const { user } = useAuth();
  const template = templates.find(t => t.id === activity.template) || templates[0];
  async function action(kind: string) {
    setBusy(true); setError('');
    try {
      if (kind === 'delete') { await api(`activities/${activity.id}/`, { method: 'DELETE' }); setRemove(false); }
      if (kind === 'duplicate') { await post(`activities/${activity.id}/duplicate/`, {}); setNotice('Cópia salva em Minhas atividades.'); }
      if (kind === 'favorite') { await api('favorites/', { method: saved ? 'DELETE' : 'POST', body: JSON.stringify({ activity_id: activity.id }) }); setSaved(!saved); }
      if (kind === 'publish' || kind === 'unpublish') await post(`activities/${activity.id}/${kind}/`, {});
      onChange?.();
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  return <article className="activity-card"><div className={`activity-art ${template.color}`}><span className="art-subject">{activity.subject}</span><span className="art-symbol">{template.symbol}</span><span className="art-dots">✧</span>{own && <span className={`status-badge ${activity.published ? 'published' : ''}`}>{activity.published ? 'Publicada' : 'Rascunho'}</span>}</div><div className="activity-content"><div className="activity-meta"><span>{template.name}</span><span>{activity.school_year}</span></div><h3>{activity.title}</h3><p className="card-description">{activity.description || 'Uma nova oportunidade de aprender e descobrir.'}</p><div className="card-details"><span><BookOpen size={13}/>{activity.questions?.length ?? activity.question_count} perguntas</span><span><Play size={12}/>{activity.plays} jogadas</span></div><div className="card-actions">{(!own || activity.published) ? <Link className="play-link" href={`/jogar/?codigo=${activity.code}`}><Play size={15}/> Jogar</Link> : <button className="play-link" disabled={busy} onClick={() => action('publish')}>Publicar <ArrowRight size={15}/></button>}<div>{own && <><Link className="icon-button" title="Editar" aria-label={`Editar ${activity.title}`} href={`/dashboard/atividades/criar/?id=${activity.id}`}><Pencil size={16}/></Link>{activity.published && <button className="icon-button" title="Compartilhar" aria-label={`Compartilhar ${activity.title}`} onClick={() => setShare(true)}><Share2 size={16}/></button>}</>}{user && user.role !== 'STUDENT' && <button disabled={busy} className="icon-button" title="Duplicar" aria-label={`Duplicar ${activity.title}`} onClick={() => action('duplicate')}><Copy size={16}/></button>}{own ? <button className="icon-button" title="Excluir" aria-label={`Excluir ${activity.title}`} onClick={() => setRemove(true)}><Trash2 size={16}/></button> : user && <button className="icon-button" title="Favoritar" aria-label={`Favoritar ${activity.title}`} disabled={busy} onClick={() => action('favorite')}><Heart size={16} fill={saved ? 'currentColor' : 'none'}/></button>}</div></div>{own && activity.published && <button className="subtle-link" disabled={busy} onClick={() => action('unpublish')}>Retirar publicação</button>}<ErrorMessage message={error}/>{notice && <p role="status" className="small-text">{notice}</p>}</div>{share && <ShareModal activity={activity} close={() => setShare(false)}/>} {remove && <Modal title="Excluir esta atividade?" close={() => setRemove(false)}><p>“{activity.title}” e seus resultados serão excluídos. Esta ação não pode ser desfeita.</p><div className="modal-actions"><button className="button secondary" onClick={() => setRemove(false)}>Cancelar</button><button className="button danger" disabled={busy} onClick={() => action('delete')}>Excluir atividade</button></div><ErrorMessage message={error}/></Modal>}</article>;
}

export function ActivityList({ mode = 'own' }: { mode?: 'own' | 'explore' | 'favorites' }) {
  const [items, setItems] = useState<Activity[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [query, setQuery] = useState(''); const [subject, setSubject] = useState(''); const [template, setTemplate] = useState('');
  const load = async () => { try { setItems(await api<Activity[]>(mode === 'own' ? 'activities/' : mode === 'favorites' ? 'favorites/' : 'explore/')); setError(''); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [mode]); // endpoints are fixed by mode
  const filtered = items.filter(a => `${a.title} ${a.subject}`.toLocaleLowerCase().includes(query.toLocaleLowerCase()) && (!subject || a.subject === subject) && (!template || a.template === template));
  return <><PageHeading eyebrow={mode === 'explore' ? 'IDEIAS PARA SUA PRÓXIMA AULA' : 'SEU REPERTÓRIO'} title={{ own: 'Minhas atividades', explore: 'Uma biblioteca de descobertas.', favorites: 'Suas ideias favoritas' }[mode]} subtitle={{ own: 'Cada atividade é um novo jeito de conectar sua turma.', explore: 'Encontre uma atividade, jogue ou adapte para sua turma.', favorites: 'Guarde por aqui as atividades que inspiram você.' }[mode]}>{mode === 'own' && <Link className="button" href="/dashboard/atividades/criar/"><Plus size={17}/> Criar atividade</Link>}</PageHeading><div className="filters"><div className="search-input"><Search size={18}/><input placeholder="Buscar uma atividade…" aria-label="Buscar atividade" value={query} onChange={e => setQuery(e.target.value)}/></div><select aria-label="Filtrar por matéria" value={subject} onChange={e => setSubject(e.target.value)}><option value="">Todas as matérias</option>{subjects.map(s => <option key={s}>{s}</option>)}</select><select aria-label="Filtrar por formato" value={template} onChange={e => setTemplate(e.target.value)}><option value="">Todos os formatos</option>{templates.map(t => <option key={t.id} value={t.id}>{t.name}</option>)}</select></div><ErrorMessage message={error}/>{error && <button className="button secondary" onClick={load}>Tentar novamente</button>}{loading ? <Loading/> : filtered.length ? <><p className="results-count">{filtered.length} {filtered.length === 1 ? 'atividade' : 'atividades'}</p><div className="activity-grid">{filtered.map(a => <ActivityCard key={a.id} activity={a} own={mode === 'own'} initiallySaved={mode === 'favorites'} onChange={load}/>)}</div></> : !error && <Empty title="Novas ideias começam por aqui."><p>{query || subject || template ? 'Nenhuma atividade encontrada. Experimente outros filtros.' : mode === 'own' ? 'Crie sua primeira atividade e compartilhe com sua turma.' : 'Ainda não há atividades neste espaço.'}</p></Empty>}</>;
}

export function Overview() {
  const { user } = useAuth(); const [items, setItems] = useState<Activity[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = async () => { try { setItems(await api<Activity[]>('activities/')); } catch (e) { setError((e as Error).message); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, []);
  return <><PageHeading eyebrow="BEM-VINDO AO SEU ESPAÇO" title={`Olá, ${user?.name.split(' ')[0] || 'professor(a)'}!`} subtitle="Que descoberta vamos criar hoje?"/><div className="welcome-banner"><div><span className="eyebrow">CADA AULA, UMA NOVA POSSIBILIDADE</span><h2>Sua próxima ideia<br/>pode virar um jogo.</h2><p>Crie uma vez. Explore diferentes jeitos de ensinar.</p><Link href={user?.role === 'STUDENT' ? '/jogar/' : '/dashboard/atividades/criar/'} className="button cream">{user?.role === 'STUDENT' ? 'Entrar em uma atividade' : 'Criar uma atividade'} <ArrowRight size={17}/></Link></div><div className="banner-shapes" aria-hidden="true"><span>✳</span><span>✦</span><span>↗</span></div></div><ErrorMessage message={error}/><div className="stats-grid">{[[BookOpen, items.length, 'Atividades criadas'], [Play, items.reduce((n, a) => n + a.plays, 0), 'Partidas concluídas'], [Users, items.filter(a => a.published).length, 'Atividades publicadas']].map(([Icon, value, label], i) => { const I = Icon as typeof BookOpen; return <div className="stat" key={i}><span><I size={21}/></span><div><strong>{String(value)}</strong><p>{String(label)}</p></div></div>; })}</div><div className="section-heading compact"><h2>Continue suas descobertas</h2><Link href="/dashboard/atividades/">Ver todas <ArrowRight size={16}/></Link></div>{loading ? <Loading/> : items.length ? <div className="activity-grid">{items.slice(0, 3).map(a => <ActivityCard key={a.id} activity={a} own onChange={load}/>)}</div> : <Empty title="Sua primeira atividade está por vir."><p>Comece com uma pergunta. O resto a gente constrói junto.</p><Link className="button secondary" href="/dashboard/atividades/criar/">Criar minha primeira atividade</Link></Empty>}<div className="section-heading compact"><h2>Um conteúdo, cinco possibilidades</h2></div><div className="template-grid small-templates">{templates.map(t => <Link className={`template-card ${t.color}`} key={t.id} href={`/dashboard/atividades/criar/?template=${t.id}`}><span className="template-symbol">{t.symbol}</span><h3>{t.name}</h3></Link>)}</div></>;
}
