'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import { Sparkles, ArrowRight } from 'lucide-react';
import { post } from '@/lib/api';
import { Activity, subjects } from '@/lib/types';
import { PageHeading, ErrorMessage } from './ui';
export function AICreator() {
  const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const router = useRouter();
  async function submit(e: React.FormEvent<HTMLFormElement>) { e.preventDefault(); setBusy(true); setError(''); const data = Object.fromEntries(new FormData(e.currentTarget)); try { const draft = await post<Activity>('ai/generate-activity/', { ...data, count: Number(data.count) }, undefined, AbortSignal.timeout(135000)); sessionStorage.setItem('entrelacos-ai-draft', JSON.stringify(draft)); router.push('/dashboard/atividades/criar/?ia=1'); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } }
  return <><PageHeading eyebrow="UM PONTO DE PARTIDA PARA SUA CRIATIVIDADE" title="Sua ideia, com uma mãozinha da IA." subtitle="Descreva o tema. Depois, revise e personalize cada pergunta no editor."/><div className="ai-layout"><form className="editor-panel" onSubmit={submit}><span className="ai-form-icon"><Sparkles size={30}/></span><h2>O que vamos descobrir hoje?</h2><ErrorMessage message={error}/><label>Tema ou instrução pedagógica<textarea name="topic" placeholder="Ex.: O ciclo da água, com exemplos do dia a dia dos alunos." required maxLength={300}/></label><div className="form-grid"><label>Matéria<select name="subject">{subjects.map(s => <option key={s}>{s}</option>)}</select></label><label>Ano escolar<select name="school_year" defaultValue="6º ano">{Array.from({ length: 9 }, (_, i) => <option key={i}>{i + 1}º ano</option>)}</select></label><label>Quantidade de perguntas<input name="count" type="number" min={1} max={20} defaultValue={5} required/></label><label>Dificuldade<select name="difficulty" defaultValue="Média"><option>Fácil</option><option>Média</option><option>Difícil</option></select></label></div><button className="button full" disabled={busy}><Sparkles size={17}/>{busy ? 'Preparando suas perguntas…' : 'Gerar rascunho de atividade'} {!busy && <ArrowRight size={17}/>}</button>{busy && <p role="status" className="small-text">Isso pode levar até dois minutos. Aguarde a revisão no editor.</p>}</form><aside className="ai-tips"><p className="eyebrow">SEU OLHAR FAZ A DIFERENÇA</p><h2>A IA propõe.<br/>Você transforma.</h2><p>Use o rascunho como ponto de partida para uma atividade com a cara da sua turma.</p><ul><li>Seja específico sobre o tema.</li><li>Informe o nível da turma.</li><li>Confira fatos e respostas antes de publicar.</li><li>Não envie informações pessoais dos alunos.</li></ul><span className="tips-star">✳</span></aside></div></>;
}
