'use client';
import { useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Plus, Trash2, ArrowRight, ArrowLeft, Check, Sparkles, Save } from 'lucide-react';
import Link from 'next/link';
import { Activity, Question, subjects, templates, Template } from '@/lib/types';
import { api, post } from '@/lib/api';
import { ErrorMessage, Loading, PageHeading } from './ui';
const blank = (): Question => ({ text: '', explanation: '', answers: [{ text: '', correct: true }, { text: '', correct: false }, { text: '', correct: false }, { text: '', correct: false }] });
export function Editor() {
  const [step, setStep] = useState(0); const [id, setId] = useState(''); const [title, setTitle] = useState(''); const [description, setDescription] = useState(''); const [subject, setSubject] = useState('Ciências'); const [year, setYear] = useState('6º ano'); const [visibility, setVisibility] = useState('link'); const [template, setTemplate] = useState<Template>('quiz'); const [questions, setQuestions] = useState<Question[]>([blank()]); const [busy, setBusy] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const router = useRouter();
  function fill(a: Activity) { setTitle(a.title); setDescription(a.description); setSubject(a.subject); setYear(a.school_year); setVisibility(a.visibility); setTemplate(a.template); setQuestions(a.questions); }
  useEffect(() => { const params = new URLSearchParams(window.location.search); const edit = params.get('id'); const format = params.get('template'); if (templates.some(t => t.id === format)) setTemplate(format as Template); if (edit) { setId(edit); api<Activity>(`activities/${edit}/`).then(fill).catch(e => setError(e.message)).finally(() => setLoading(false)); } else { if (params.has('ia')) { const draft = sessionStorage.getItem('entrelacos-ai-draft'); if (draft) { try { fill(JSON.parse(draft)); } catch { setError('O rascunho não pôde ser recuperado.'); } } } setLoading(false); } }, []);
  const update = (index: number, question: Question) => setQuestions(qs => qs.map((q, i) => i === index ? question : q));
  function next() {
    setError('');
    if (step === 0 && !title.trim()) { setError('Dê um título à sua atividade.'); return; }
    if (step === 1 && questions.some(q => !q.text.trim() || q.answers.some(a => !a.text.trim()) || q.answers.filter(a => a.correct).length !== 1 || new Set(q.answers.map(a => a.text.trim().toLowerCase())).size !== q.answers.length)) { setError('Preencha cada pergunta e suas alternativas, sem repetições. Marque uma resposta correta.'); return; }
    setStep(step + 1); window.scrollTo(0, 0);
  }
  async function save(publish: boolean) {
    setBusy(true); setError('');
    try {
      const data = { title, description, subject, school_year: year, visibility, template, language: 'pt-BR', questions };
      const saved = await api<Activity>(id ? `activities/${id}/` : 'activities/', { method: id ? 'PUT' : 'POST', body: JSON.stringify(data) });
      setId(saved.id);
      if (publish) await post(`activities/${saved.id}/publish/`, {});
      sessionStorage.removeItem('entrelacos-ai-draft'); router.push('/dashboard/atividades/');
    } catch (e) { setError((e as Error).message); } finally { setBusy(false); }
  }
  if (loading) return <Loading/>;
  return <><PageHeading eyebrow="ATELIÊ DE ATIVIDADES" title={id ? 'Vamos lapidar sua ideia.' : 'Uma nova descoberta começa aqui.'} subtitle="Seu conteúdo pode ganhar diferentes formas de jogar."/><div className="editor-steps">{['Sua ideia', 'Conteúdo', 'Formato', 'Publicar'].map((s, i) => <div className={i <= step ? 'active' : ''} key={s}><span>{i < step ? <Check size={15}/> : i + 1}</span>{s}</div>)}</div><ErrorMessage message={error}/><div className="editor-panel">
    {step === 0 && <><div className="editor-title"><h2>Conte um pouco sobre sua atividade.</h2><Link href="/dashboard/ia/" className="text-button"><Sparkles size={16}/> Criar com IA</Link></div><label>Título da atividade<input placeholder="Ex.: Uma viagem pelo Sistema Solar" value={title} maxLength={160} onChange={e => setTitle(e.target.value)} required/></label><label>Descrição<textarea placeholder="O que sua turma vai descobrir?" value={description} maxLength={2000} onChange={e => setDescription(e.target.value)}/></label><div className="form-grid"><label>Matéria<select value={subject} onChange={e => setSubject(e.target.value)}>{subjects.map(s => <option key={s}>{s}</option>)}</select></label><label>Ano escolar<select value={year} onChange={e => setYear(e.target.value)}>{['Educação infantil', ...Array.from({ length: 9 }, (_, i) => `${i + 1}º ano`), 'Ensino médio', 'Outros'].map(y => <option key={y}>{y}</option>)}</select></label></div></>}
    {step === 1 && <><h2>O que vamos aprender?</h2><p className="muted">Adicione perguntas e marque a alternativa correta. Os jogos reutilizam esse conteúdo.</p>{questions.map((q, i) => <section className="question-editor" key={i}><div className="question-heading"><b>Pergunta {i + 1}</b><button className="icon-button" aria-label={`Excluir pergunta ${i + 1}`} disabled={questions.length === 1} onClick={() => setQuestions(questions.filter((_, n) => n !== i))}><Trash2 size={16}/></button></div><label>Enunciado<textarea value={q.text} maxLength={1000} placeholder="Escreva sua pergunta…" onChange={e => update(i, { ...q, text: e.target.value })}/></label><span className="field-label">Alternativas · selecione a correta</span>{q.answers.map((answer, j) => <div className={`answer-editor ${answer.correct ? 'selected' : ''}`} key={j}><input type="radio" name={`correct-${i}`} aria-label={`Alternativa ${j + 1} correta da pergunta ${i + 1}`} checked={answer.correct} onChange={() => update(i, { ...q, answers: q.answers.map((a, n) => ({ ...a, correct: n === j })) })}/><input aria-label={`Alternativa ${j + 1} da pergunta ${i + 1}`} placeholder={`Alternativa ${String.fromCharCode(65 + j)}`} value={answer.text} maxLength={500} onChange={e => update(i, { ...q, answers: q.answers.map((a, n) => n === j ? { ...a, text: e.target.value } : a) })}/>{q.answers.length > 2 && <button className="icon-button" aria-label={`Remover alternativa ${j + 1}`} onClick={() => update(i, { ...q, answers: q.answers.filter((_, n) => n !== j).map((a, n) => ({ ...a, correct: answer.correct ? n === 0 : a.correct })) })}><Trash2 size={14}/></button>}</div>)}{q.answers.length < 6 && <button className="subtle-link" onClick={() => update(i, { ...q, answers: [...q.answers, { text: '', correct: false }] })}>+ Adicionar alternativa</button>}<label>Explicação (opcional)<input value={q.explanation} maxLength={1500} placeholder="Ajude o aluno a entender a resposta." onChange={e => update(i, { ...q, explanation: e.target.value })}/></label></section>)}<button className="button secondary full" disabled={questions.length >= 50} onClick={() => setQuestions([...questions, blank()])}><Plus size={17}/> Adicionar pergunta</button></>}
    {step === 2 && <><h2>Como sua turma vai jogar?</h2><p className="muted">O formato é só o começo. Você pode trocá-lo depois.</p><div className="format-options">{templates.map(t => <button className={`format-option ${t.color} ${template === t.id ? 'selected-format' : ''}`} key={t.id} onClick={() => setTemplate(t.id)}><span className="template-symbol">{t.symbol}</span><h3>{t.name}</h3><p>{t.description}</p>{template === t.id && <Check className="format-check" size={20}/>}</button>)}</div><p className="small-text">Verdadeiro ou falso transforma cada pergunta em uma associação para julgar. Flashcards são um modo de estudo com autoavaliação.</p></>}
    {step === 3 && <><h2>Pronta para encontrar sua turma.</h2><div className="publish-summary"><span className="template-symbol">{templates.find(t => t.id === template)?.symbol}</span><div><h3>{title}</h3><p>{subject} · {year} · {questions.length} perguntas</p><span className="badge">{templates.find(t => t.id === template)?.name}</span></div></div><label>Quem pode acessar?<select value={visibility} onChange={e => setVisibility(e.target.value)}><option value="link">Quem tiver o link ou código</option><option value="public">Todos · aparecer na biblioteca pública</option><option value="private">Somente eu</option></select></label><p className="small-text">Ao publicar, sua atividade ganha um código e um link para compartilhar. Revise as perguntas antes de enviar para os alunos.</p></>}
    <div className="editor-footer">{step > 0 ? <button className="button secondary" onClick={() => { setStep(step - 1); setError(''); }} disabled={busy}><ArrowLeft size={16}/> Voltar</button> : <Link href="/dashboard/atividades/" className="text-button">Cancelar</Link>}{step < 3 ? <button className="button" onClick={next}>Continuar <ArrowRight size={16}/></button> : <div className="actions"><button className="button secondary" disabled={busy} onClick={() => save(false)}><Save size={16}/> Salvar</button><button className="button" disabled={busy} onClick={() => save(true)}>{busy ? 'Salvando…' : 'Publicar atividade'} <ArrowRight size={16}/></button></div>}</div></div></>;
}
