'use client';
import { useEffect, useState } from 'react';
import { Activity, GameResult } from '@/lib/types';
import { api } from '@/lib/api';
import { PageHeading, Loading, ErrorMessage, Empty } from './ui';
import { Download } from 'lucide-react';
export function Reports() {
  const [activities, setActivities] = useState<Activity[]>([]); const [selected, setSelected] = useState(''); const [results, setResults] = useState<GameResult[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  useEffect(() => { api<Activity[]>('activities/').then(a => { setActivities(a); if (a[0]) setSelected(a[0].id); }).catch(e => setError(e.message)).finally(() => setLoading(false)); }, []);
  useEffect(() => { if (!selected) return; let active = true; setLoading(true); setError(''); api<GameResult[]>(`activities/${selected}/results/`).then(r => { if (active) setResults(r); }).catch(e => { if (active) setError(e.message); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [selected]);
  const competitive = results.filter(r => r.template !== 'flashcards');
  const average = competitive.length ? Math.round(competitive.reduce((s, r) => s + r.percentage, 0) / competitive.length) : 0;
  function download() {
    const cell = (s: string) => `"${(/^[=+@\-\t\r]/.test(s) ? "'" + s : s).replaceAll('"', '""')}"`;
    const text = '\uFEFF' + [['Participante', 'Formato', 'Acertos', 'Total', 'Pontos', 'Tempo (s)'], ...results.map(r => [r.name, r.template, String(r.correct), String(r.total), String(r.score), String(r.seconds)])].map(row => row.map(cell).join(';')).join('\r\n');
    const url = URL.createObjectURL(new Blob([text], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = 'resultados-entrelacos.csv'; link.click(); URL.revokeObjectURL(url);
  }
  return <><PageHeading eyebrow="ACOMPANHAR PARA ENSINAR MELHOR" title="Cada resultado conta uma história." subtitle="Veja como sua turma está aprendendo, uma atividade de cada vez.">{results.length > 0 && <button className="button secondary" onClick={download}><Download size={16}/> Exportar CSV</button>}</PageHeading><label className="report-select">Escolha a atividade<select value={selected} onChange={e => setSelected(e.target.value)}><option value="" disabled>Selecione uma atividade</option>{activities.map(a => <option value={a.id} key={a.id}>{a.title}</option>)}</select></label><ErrorMessage message={error}/>{loading ? <Loading/> : results.length ? <><div className="stats-grid"><div className="stat"><div><strong>{results.length}</strong><p>Partidas concluídas</p></div></div><div className="stat"><div><strong>{average}%</strong><p>Média de acertos · jogos avaliados</p></div></div><div className="stat"><div><strong>{Math.round(results.reduce((s, r) => s + r.seconds, 0) / results.length)}s</strong><p>Tempo médio</p></div></div></div><div className="table-wrap"><table><thead><tr><th>Participante</th><th>Formato</th><th>Acertos</th><th>Pontos</th><th>Tempo</th></tr></thead><tbody>{results.map(r => <tr key={r.id}><td><b>{r.name}</b></td><td>{r.template === 'flashcards' ? 'Flashcards · autoavaliação' : r.template}</td><td><span className="badge">{r.correct}/{r.total} · {r.percentage}%</span></td><td>{r.score}</td><td>{r.seconds}s</td></tr>)}</tbody></table></div><h2 className="report-heading">Aprendizagem por pergunta</h2><p className="small-text">Jogos avaliados. Flashcards não entram na média. Edições da atividade preservam os resultados anteriores.</p><div className="question-report">{activities.find(a => a.id === selected)?.questions.map((q, i) => { const responses = competitive.flatMap(r => r.responses).filter(r => r.question_id === q.id); const percent = responses.length ? Math.round(responses.filter(r => r.correct).length / responses.length * 100) : 0; return <div key={q.id}><b>{i + 1}. {q.text}</b><div className="progress-track"><div style={{ width: `${percent}%` }}/></div><span>{responses.length ? `${percent}% de acertos · ${responses.length} respostas` : 'Sem respostas nesta versão'}</span></div>; })}</div></> : !error && <Empty title="As descobertas vão aparecer aqui."><p>Publique uma atividade e compartilhe com seus alunos. Os resultados aparecem após a conclusão de cada partida.</p></Empty>}</>;
}
