# Generated by Django 5.2.17 on 2026-09-19 15:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['creator', '-updated_at'], name='activity_owner_recent'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['published', 'visibility', '-updated_at'], name='activity_public_recent'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['activity', 'finished_at'], name='game_activity_finished'),
        ),
        migrations.AddIndex(
            model_name='game',
            index=models.Index(fields=['activity', 'template', '-score', 'finished_at'], name='game_activity_ranking'),
        ),
    ]
